#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${AGENT_DB_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${AGENT_DB_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${AGENT_DB_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON game_embeddings TO ${AGENT_DB_USER};
    ALTER INDEX my-hnsw-index OWNER TO ${AGENT_DB_USER};
    ALTER INDEX my-ivfflat OWNER TO ${AGENT_DB_USER};
    ALTER INDEX game_embeddings_fts_idx TO ${AGENT_DB_USER};
EOSQL
